[package]
name = "webauthn-tiny"
version = "0.1.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
argon2 = "0.4.1"
async-trait = "0.1.59"
axum = "0.6.1"
axum-macros = "0.3.0"
axum-sessions = "0.4.1"
base64 = "0.13.1"
clap = { version = "4.0.29", features = ["std", "derive", "env"] }
libsqlite3-sys = "0.25.2"
liquid = "0.26.0"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
mime_guess = "2.0.4"
rusqlite = "0.28.0"
rust-embed = { version = "6.4.2", features = ["interpolate-folder-path"] }
serde = "1.0.148"
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
tokio-rusqlite = "0.3.0"
tower = { version = "0.4.13", features = ["tracing"] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = "1.2.2"
webauthn-authenticator-rs = "0.4.9"
webauthn-rs = { version = "0.4.8", features = [
  "danger-allow-state-serialisation",
  "danger-credential-internals",
  "resident-key-support",
] }
webauthn-rs-core = "0.4.9"
webauthn-rs-proto = "0.4.9"
