[package]
name = "webauthn-tiny"
version = "0.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
axum = "0.5.17"
axum-macros = "0.2.3"
axum-sessions = "0.3.2"
clap = { version = "4.0.24", features = ["std", "derive", "env"] }
libsqlite3-sys = "0.25.2"
liquid = "0.26.0"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
mime_guess = "2.0.4"
rusqlite = "0.28.0"
rust-embed = { version = "6.4.2", features = ["interpolate-folder-path"] }
serde = "1.0.147"
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
tokio-rusqlite = "0.3.0"
tower = { version = "0.4.13", features = ["tracing"] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = "1.2.1"
webauthn-authenticator-rs = "0.4.8"
webauthn-rs = { version = "0.4.8", features = [
  "danger-allow-state-serialisation",
  "danger-credential-internals",
  "resident-key-support",
] }
webauthn-rs-core = "0.4.8"
webauthn-rs-proto = "0.4.8"
