[package]
name = "webauthn-tiny"
version = "0.2.3"
edition = "2021"

[profile.release]
strip = true

[dependencies]
anyhow = "1.0.75"
argon2 = "0.4.1"
async-trait = "0.1.73"
axum = "0.6.20"
axum-macros = "0.3.8"
axum-sessions = "0.4.1"
base64 = "0.21.2"
clap = { version = "4.3.23", features = ["std", "derive", "env"] }
libsqlite3-sys = "0.25.2"
liquid = "0.26.4"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
mime_guess = "2.0.4"
rusqlite = "0.28.0"
rust-embed = { version = "6.8.1", features = ["interpolate-folder-path"] }
serde = "1.0.183"
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tokio-rusqlite = "0.3.0"
tower = { version = "0.4.13", features = ["tracing"] }
tower-http = { version = "0.3.5", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = "1.4.1"
webauthn-authenticator-rs = "0.4.9"
webauthn-rs = { version = "0.4.8", features = [
  "danger-allow-state-serialisation",
  "danger-credential-internals",
  "resident-key-support",
] }
webauthn-rs-core = "0.4.9"
webauthn-rs-proto = "0.4.9"
